name: ci

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  eslint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies Frontend
        run: npm ci

      - name: Test Frontend
        run: npm run test
        env:
          VITE_SUPABASE_URL: https://fdnzbbyiwwzvandoyopt.supabase.co
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
          VITE_SENTRY_DSN: https://4a816694c0f6c51d0258edb9e56a5eb2@o4508337282613248.ingest.us.sentry.io/4508337839865856

  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 18

      - name: Install dependencies Frontend
        run: npm ci

      - name: Start Vite server
        run: npm run dev &

      - name: Wait for Vite server to start
        run: |
          until curl -s -o /dev/null http://localhost:5173; do
            echo "Waiting for Vite server to start..."
            sleep 5
          done

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
